import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import { TopNav } from "./_components/TopNav";
import { ClerkProvider } from '@clerk/nextjs'
import { type Metadata } from "next";
import { ViewTransitions } from "next-view-transitions";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dillon Rose",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ViewTransitions>
      <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}>
          <main className="flex flex-col h-full">
            <TopNav />
            {children}
            <Footer />
          </main>
        </body>
      </html>
      </ClerkProvider>
    </ViewTransitions>
  );
}

function Footer() {
  const links = [
    { name: 'x', url: 'https://x.com/_Dillon_Rose_' },
    { name: 'linkedin', url: 'https://www.linkedin.com/in/dillonmrose' },
    { name: 'github', url: 'https://github.com/dillonmrose' },
  ];

  return (
    <footer className="mt-12 text-center">
      <div className="flex justify-center space-x-4 tracking-tight">
        {links.map((link) => (
          <a
            key={link.name}
            href={link.url}
            target="_blank"
            rel="noopener noreferrer"
            className="text-gray-400 hover:text-blue-500 transition-colors duration-200"
          >
            {link.name}
          </a>
        ))}
      </div>
    </footer>
  );
}